/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue */

#ifndef _Included_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
#define _Included_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_open
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    openReadOnly
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_openReadOnly
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_close
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    listFiles
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_listFiles
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    listLocationFiles
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_listLocationFiles
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    listFileLocations
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_listFileLocations
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    locationExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_locationExists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    addLocation
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_addLocation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    removeLocation
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_removeLocation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    addFileToCollection
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_addFileToCollection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    addFileToLocation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_addFileToLocation
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    removeFileFromCollection
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_removeFileFromCollection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue
 * Method:    removeFileFromLocation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridReplicaCatalogue_removeFileFromLocation
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
