/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridMessageSender */

#ifndef _Included_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridMessageSender
#define _Included_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridMessageSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridMessageSender
 * Method:    doSend
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridMessageSender_doSend
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridMessageSender
 * Method:    activateGlobusIOModule
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridMessageSender_activateGlobusIOModule
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
