/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient */

#ifndef _Included_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
#define _Included_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: theClient */
/* Inaccessible static: usingSecondary */
#undef uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NODE_OK
#define uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NODE_OK 0L
#undef uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NODE_DEAD
#define uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NODE_DEAD 1L
#undef uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NODE_DISABLED
#define uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NODE_DISABLED 2L
#undef uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NODE_RETIRING
#define uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NODE_RETIRING 3L
#undef uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NORMAL_NODE
#define uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_NORMAL_NODE 0L
#undef uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_PRIMARY_NODE
#define uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_PRIMARY_NODE 1L
#undef uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_SECONDARY_NODE
#define uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_SECONDARY_NODE 2L
/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    init
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_init
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    addNode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_addNode
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    removeNode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_removeNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    disableNode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_disableNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    enableNode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_enableNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    retireNode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_retireNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    unretireNode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_unretireNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    getFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_getFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    getDirectory
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_getDirectory
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    putFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_putFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    putDirectory
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_putDirectory
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    list
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_list
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    listNodes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_listNodes
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    getNodeSite
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_getNodeSite
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    getMainNodeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_getMainNodeName
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    getMetadataCatalogueLocation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_getMetadataCatalogueLocation
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    getNodeStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_getNodeStatus
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    getNodeType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_getNodeType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    deleteFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_deleteFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    deleteDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_deleteDirectory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    touchFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_touchFile__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    touchDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_touchDirectory__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    touchFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_touchFile__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient
 * Method:    touchDirectory
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ed_epcc_qcdgrid_datagrid_QCDgridClient_touchDirectory__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
