/* soapClient.c
   Generated by gSOAP 2.7.15 from srm2_2.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.15 2010-02-01 14:30:37 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmReserveSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmReserveSpaceRequest *srmReserveSpaceRequest, struct ns1__srmReserveSpaceResponse_ *_param_1)
{	struct ns1__srmReserveSpace soap_tmp_ns1__srmReserveSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmReserveSpace.srmReserveSpaceRequest = srmReserveSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmReserveSpace(soap, &soap_tmp_ns1__srmReserveSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmReserveSpace(soap, &soap_tmp_ns1__srmReserveSpace, "ns1:srmReserveSpace", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmReserveSpace(soap, &soap_tmp_ns1__srmReserveSpace, "ns1:srmReserveSpace", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__srmReserveSpaceResponse_(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmReserveSpaceResponse_(soap, _param_1, "ns1:srmReserveSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmStatusOfReserveSpaceRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmStatusOfReserveSpaceRequestRequest *srmStatusOfReserveSpaceRequestRequest, struct ns1__srmStatusOfReserveSpaceRequestResponse_ *_param_2)
{	struct ns1__srmStatusOfReserveSpaceRequest soap_tmp_ns1__srmStatusOfReserveSpaceRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmStatusOfReserveSpaceRequest.srmStatusOfReserveSpaceRequestRequest = srmStatusOfReserveSpaceRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmStatusOfReserveSpaceRequest(soap, &soap_tmp_ns1__srmStatusOfReserveSpaceRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmStatusOfReserveSpaceRequest(soap, &soap_tmp_ns1__srmStatusOfReserveSpaceRequest, "ns1:srmStatusOfReserveSpaceRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmStatusOfReserveSpaceRequest(soap, &soap_tmp_ns1__srmStatusOfReserveSpaceRequest, "ns1:srmStatusOfReserveSpaceRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_2)
		return soap_closesock(soap);
	soap_default_ns1__srmStatusOfReserveSpaceRequestResponse_(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmStatusOfReserveSpaceRequestResponse_(soap, _param_2, "ns1:srmStatusOfReserveSpaceRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmReleaseSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmReleaseSpaceRequest *srmReleaseSpaceRequest, struct ns1__srmReleaseSpaceResponse_ *_param_3)
{	struct ns1__srmReleaseSpace soap_tmp_ns1__srmReleaseSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmReleaseSpace.srmReleaseSpaceRequest = srmReleaseSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmReleaseSpace(soap, &soap_tmp_ns1__srmReleaseSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmReleaseSpace(soap, &soap_tmp_ns1__srmReleaseSpace, "ns1:srmReleaseSpace", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmReleaseSpace(soap, &soap_tmp_ns1__srmReleaseSpace, "ns1:srmReleaseSpace", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_3)
		return soap_closesock(soap);
	soap_default_ns1__srmReleaseSpaceResponse_(soap, _param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmReleaseSpaceResponse_(soap, _param_3, "ns1:srmReleaseSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmUpdateSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmUpdateSpaceRequest *srmUpdateSpaceRequest, struct ns1__srmUpdateSpaceResponse_ *_param_4)
{	struct ns1__srmUpdateSpace soap_tmp_ns1__srmUpdateSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmUpdateSpace.srmUpdateSpaceRequest = srmUpdateSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmUpdateSpace(soap, &soap_tmp_ns1__srmUpdateSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmUpdateSpace(soap, &soap_tmp_ns1__srmUpdateSpace, "ns1:srmUpdateSpace", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmUpdateSpace(soap, &soap_tmp_ns1__srmUpdateSpace, "ns1:srmUpdateSpace", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_4)
		return soap_closesock(soap);
	soap_default_ns1__srmUpdateSpaceResponse_(soap, _param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmUpdateSpaceResponse_(soap, _param_4, "ns1:srmUpdateSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmStatusOfUpdateSpaceRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmStatusOfUpdateSpaceRequestRequest *srmStatusOfUpdateSpaceRequestRequest, struct ns1__srmStatusOfUpdateSpaceRequestResponse_ *_param_5)
{	struct ns1__srmStatusOfUpdateSpaceRequest soap_tmp_ns1__srmStatusOfUpdateSpaceRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmStatusOfUpdateSpaceRequest.srmStatusOfUpdateSpaceRequestRequest = srmStatusOfUpdateSpaceRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmStatusOfUpdateSpaceRequest(soap, &soap_tmp_ns1__srmStatusOfUpdateSpaceRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmStatusOfUpdateSpaceRequest(soap, &soap_tmp_ns1__srmStatusOfUpdateSpaceRequest, "ns1:srmStatusOfUpdateSpaceRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmStatusOfUpdateSpaceRequest(soap, &soap_tmp_ns1__srmStatusOfUpdateSpaceRequest, "ns1:srmStatusOfUpdateSpaceRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_5)
		return soap_closesock(soap);
	soap_default_ns1__srmStatusOfUpdateSpaceRequestResponse_(soap, _param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmStatusOfUpdateSpaceRequestResponse_(soap, _param_5, "ns1:srmStatusOfUpdateSpaceRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmGetSpaceMetaData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmGetSpaceMetaDataRequest *srmGetSpaceMetaDataRequest, struct ns1__srmGetSpaceMetaDataResponse_ *_param_6)
{	struct ns1__srmGetSpaceMetaData soap_tmp_ns1__srmGetSpaceMetaData;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmGetSpaceMetaData.srmGetSpaceMetaDataRequest = srmGetSpaceMetaDataRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmGetSpaceMetaData(soap, &soap_tmp_ns1__srmGetSpaceMetaData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmGetSpaceMetaData(soap, &soap_tmp_ns1__srmGetSpaceMetaData, "ns1:srmGetSpaceMetaData", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmGetSpaceMetaData(soap, &soap_tmp_ns1__srmGetSpaceMetaData, "ns1:srmGetSpaceMetaData", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_6)
		return soap_closesock(soap);
	soap_default_ns1__srmGetSpaceMetaDataResponse_(soap, _param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmGetSpaceMetaDataResponse_(soap, _param_6, "ns1:srmGetSpaceMetaDataResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmChangeSpaceForFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmChangeSpaceForFilesRequest *srmChangeSpaceForFilesRequest, struct ns1__srmChangeSpaceForFilesResponse_ *_param_7)
{	struct ns1__srmChangeSpaceForFiles soap_tmp_ns1__srmChangeSpaceForFiles;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmChangeSpaceForFiles.srmChangeSpaceForFilesRequest = srmChangeSpaceForFilesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmChangeSpaceForFiles(soap, &soap_tmp_ns1__srmChangeSpaceForFiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmChangeSpaceForFiles(soap, &soap_tmp_ns1__srmChangeSpaceForFiles, "ns1:srmChangeSpaceForFiles", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmChangeSpaceForFiles(soap, &soap_tmp_ns1__srmChangeSpaceForFiles, "ns1:srmChangeSpaceForFiles", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_7)
		return soap_closesock(soap);
	soap_default_ns1__srmChangeSpaceForFilesResponse_(soap, _param_7);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmChangeSpaceForFilesResponse_(soap, _param_7, "ns1:srmChangeSpaceForFilesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmStatusOfChangeSpaceForFilesRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmStatusOfChangeSpaceForFilesRequestRequest *srmStatusOfChangeSpaceForFilesRequestRequest, struct ns1__srmStatusOfChangeSpaceForFilesRequestResponse_ *_param_8)
{	struct ns1__srmStatusOfChangeSpaceForFilesRequest soap_tmp_ns1__srmStatusOfChangeSpaceForFilesRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmStatusOfChangeSpaceForFilesRequest.srmStatusOfChangeSpaceForFilesRequestRequest = srmStatusOfChangeSpaceForFilesRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmStatusOfChangeSpaceForFilesRequest(soap, &soap_tmp_ns1__srmStatusOfChangeSpaceForFilesRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmStatusOfChangeSpaceForFilesRequest(soap, &soap_tmp_ns1__srmStatusOfChangeSpaceForFilesRequest, "ns1:srmStatusOfChangeSpaceForFilesRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmStatusOfChangeSpaceForFilesRequest(soap, &soap_tmp_ns1__srmStatusOfChangeSpaceForFilesRequest, "ns1:srmStatusOfChangeSpaceForFilesRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_8)
		return soap_closesock(soap);
	soap_default_ns1__srmStatusOfChangeSpaceForFilesRequestResponse_(soap, _param_8);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmStatusOfChangeSpaceForFilesRequestResponse_(soap, _param_8, "ns1:srmStatusOfChangeSpaceForFilesRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmExtendFileLifeTimeInSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmExtendFileLifeTimeInSpaceRequest *srmExtendFileLifeTimeInSpaceRequest, struct ns1__srmExtendFileLifeTimeInSpaceResponse_ *_param_9)
{	struct ns1__srmExtendFileLifeTimeInSpace soap_tmp_ns1__srmExtendFileLifeTimeInSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmExtendFileLifeTimeInSpace.srmExtendFileLifeTimeInSpaceRequest = srmExtendFileLifeTimeInSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmExtendFileLifeTimeInSpace(soap, &soap_tmp_ns1__srmExtendFileLifeTimeInSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmExtendFileLifeTimeInSpace(soap, &soap_tmp_ns1__srmExtendFileLifeTimeInSpace, "ns1:srmExtendFileLifeTimeInSpace", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmExtendFileLifeTimeInSpace(soap, &soap_tmp_ns1__srmExtendFileLifeTimeInSpace, "ns1:srmExtendFileLifeTimeInSpace", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_9)
		return soap_closesock(soap);
	soap_default_ns1__srmExtendFileLifeTimeInSpaceResponse_(soap, _param_9);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmExtendFileLifeTimeInSpaceResponse_(soap, _param_9, "ns1:srmExtendFileLifeTimeInSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmPurgeFromSpace(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmPurgeFromSpaceRequest *srmPurgeFromSpaceRequest, struct ns1__srmPurgeFromSpaceResponse_ *_param_10)
{	struct ns1__srmPurgeFromSpace soap_tmp_ns1__srmPurgeFromSpace;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmPurgeFromSpace.srmPurgeFromSpaceRequest = srmPurgeFromSpaceRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmPurgeFromSpace(soap, &soap_tmp_ns1__srmPurgeFromSpace);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmPurgeFromSpace(soap, &soap_tmp_ns1__srmPurgeFromSpace, "ns1:srmPurgeFromSpace", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmPurgeFromSpace(soap, &soap_tmp_ns1__srmPurgeFromSpace, "ns1:srmPurgeFromSpace", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_10)
		return soap_closesock(soap);
	soap_default_ns1__srmPurgeFromSpaceResponse_(soap, _param_10);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmPurgeFromSpaceResponse_(soap, _param_10, "ns1:srmPurgeFromSpaceResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmGetSpaceTokens(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmGetSpaceTokensRequest *srmGetSpaceTokensRequest, struct ns1__srmGetSpaceTokensResponse_ *_param_11)
{	struct ns1__srmGetSpaceTokens soap_tmp_ns1__srmGetSpaceTokens;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmGetSpaceTokens.srmGetSpaceTokensRequest = srmGetSpaceTokensRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmGetSpaceTokens(soap, &soap_tmp_ns1__srmGetSpaceTokens);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmGetSpaceTokens(soap, &soap_tmp_ns1__srmGetSpaceTokens, "ns1:srmGetSpaceTokens", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmGetSpaceTokens(soap, &soap_tmp_ns1__srmGetSpaceTokens, "ns1:srmGetSpaceTokens", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_11)
		return soap_closesock(soap);
	soap_default_ns1__srmGetSpaceTokensResponse_(soap, _param_11);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmGetSpaceTokensResponse_(soap, _param_11, "ns1:srmGetSpaceTokensResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmSetPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmSetPermissionRequest *srmSetPermissionRequest, struct ns1__srmSetPermissionResponse_ *_param_12)
{	struct ns1__srmSetPermission soap_tmp_ns1__srmSetPermission;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmSetPermission.srmSetPermissionRequest = srmSetPermissionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmSetPermission(soap, &soap_tmp_ns1__srmSetPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmSetPermission(soap, &soap_tmp_ns1__srmSetPermission, "ns1:srmSetPermission", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmSetPermission(soap, &soap_tmp_ns1__srmSetPermission, "ns1:srmSetPermission", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_12)
		return soap_closesock(soap);
	soap_default_ns1__srmSetPermissionResponse_(soap, _param_12);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmSetPermissionResponse_(soap, _param_12, "ns1:srmSetPermissionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmCheckPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmCheckPermissionRequest *srmCheckPermissionRequest, struct ns1__srmCheckPermissionResponse_ *_param_13)
{	struct ns1__srmCheckPermission soap_tmp_ns1__srmCheckPermission;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmCheckPermission.srmCheckPermissionRequest = srmCheckPermissionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmCheckPermission(soap, &soap_tmp_ns1__srmCheckPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmCheckPermission(soap, &soap_tmp_ns1__srmCheckPermission, "ns1:srmCheckPermission", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmCheckPermission(soap, &soap_tmp_ns1__srmCheckPermission, "ns1:srmCheckPermission", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_13)
		return soap_closesock(soap);
	soap_default_ns1__srmCheckPermissionResponse_(soap, _param_13);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmCheckPermissionResponse_(soap, _param_13, "ns1:srmCheckPermissionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmGetPermission(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmGetPermissionRequest *srmGetPermissionRequest, struct ns1__srmGetPermissionResponse_ *_param_14)
{	struct ns1__srmGetPermission soap_tmp_ns1__srmGetPermission;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmGetPermission.srmGetPermissionRequest = srmGetPermissionRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmGetPermission(soap, &soap_tmp_ns1__srmGetPermission);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmGetPermission(soap, &soap_tmp_ns1__srmGetPermission, "ns1:srmGetPermission", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmGetPermission(soap, &soap_tmp_ns1__srmGetPermission, "ns1:srmGetPermission", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_14)
		return soap_closesock(soap);
	soap_default_ns1__srmGetPermissionResponse_(soap, _param_14);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmGetPermissionResponse_(soap, _param_14, "ns1:srmGetPermissionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmMkdir(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmMkdirRequest *srmMkdirRequest, struct ns1__srmMkdirResponse_ *_param_15)
{	struct ns1__srmMkdir soap_tmp_ns1__srmMkdir;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmMkdir.srmMkdirRequest = srmMkdirRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmMkdir(soap, &soap_tmp_ns1__srmMkdir);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmMkdir(soap, &soap_tmp_ns1__srmMkdir, "ns1:srmMkdir", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmMkdir(soap, &soap_tmp_ns1__srmMkdir, "ns1:srmMkdir", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_15)
		return soap_closesock(soap);
	soap_default_ns1__srmMkdirResponse_(soap, _param_15);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmMkdirResponse_(soap, _param_15, "ns1:srmMkdirResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmRmdir(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmRmdirRequest *srmRmdirRequest, struct ns1__srmRmdirResponse_ *_param_16)
{	struct ns1__srmRmdir soap_tmp_ns1__srmRmdir;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmRmdir.srmRmdirRequest = srmRmdirRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmRmdir(soap, &soap_tmp_ns1__srmRmdir);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmRmdir(soap, &soap_tmp_ns1__srmRmdir, "ns1:srmRmdir", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmRmdir(soap, &soap_tmp_ns1__srmRmdir, "ns1:srmRmdir", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_16)
		return soap_closesock(soap);
	soap_default_ns1__srmRmdirResponse_(soap, _param_16);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmRmdirResponse_(soap, _param_16, "ns1:srmRmdirResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmRm(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmRmRequest *srmRmRequest, struct ns1__srmRmResponse_ *_param_17)
{	struct ns1__srmRm soap_tmp_ns1__srmRm;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmRm.srmRmRequest = srmRmRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmRm(soap, &soap_tmp_ns1__srmRm);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmRm(soap, &soap_tmp_ns1__srmRm, "ns1:srmRm", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmRm(soap, &soap_tmp_ns1__srmRm, "ns1:srmRm", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_17)
		return soap_closesock(soap);
	soap_default_ns1__srmRmResponse_(soap, _param_17);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmRmResponse_(soap, _param_17, "ns1:srmRmResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmLs(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmLsRequest *srmLsRequest, struct ns1__srmLsResponse_ *_param_18)
{	struct ns1__srmLs soap_tmp_ns1__srmLs;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmLs.srmLsRequest = srmLsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmLs(soap, &soap_tmp_ns1__srmLs);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmLs(soap, &soap_tmp_ns1__srmLs, "ns1:srmLs", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmLs(soap, &soap_tmp_ns1__srmLs, "ns1:srmLs", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_18)
		return soap_closesock(soap);
	soap_default_ns1__srmLsResponse_(soap, _param_18);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmLsResponse_(soap, _param_18, "ns1:srmLsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmStatusOfLsRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmStatusOfLsRequestRequest *srmStatusOfLsRequestRequest, struct ns1__srmStatusOfLsRequestResponse_ *_param_19)
{	struct ns1__srmStatusOfLsRequest soap_tmp_ns1__srmStatusOfLsRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmStatusOfLsRequest.srmStatusOfLsRequestRequest = srmStatusOfLsRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmStatusOfLsRequest(soap, &soap_tmp_ns1__srmStatusOfLsRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmStatusOfLsRequest(soap, &soap_tmp_ns1__srmStatusOfLsRequest, "ns1:srmStatusOfLsRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmStatusOfLsRequest(soap, &soap_tmp_ns1__srmStatusOfLsRequest, "ns1:srmStatusOfLsRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_19)
		return soap_closesock(soap);
	soap_default_ns1__srmStatusOfLsRequestResponse_(soap, _param_19);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmStatusOfLsRequestResponse_(soap, _param_19, "ns1:srmStatusOfLsRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmMv(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmMvRequest *srmMvRequest, struct ns1__srmMvResponse_ *_param_20)
{	struct ns1__srmMv soap_tmp_ns1__srmMv;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmMv.srmMvRequest = srmMvRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmMv(soap, &soap_tmp_ns1__srmMv);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmMv(soap, &soap_tmp_ns1__srmMv, "ns1:srmMv", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmMv(soap, &soap_tmp_ns1__srmMv, "ns1:srmMv", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_20)
		return soap_closesock(soap);
	soap_default_ns1__srmMvResponse_(soap, _param_20);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmMvResponse_(soap, _param_20, "ns1:srmMvResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmPrepareToGet(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmPrepareToGetRequest *srmPrepareToGetRequest, struct ns1__srmPrepareToGetResponse_ *_param_21)
{	struct ns1__srmPrepareToGet soap_tmp_ns1__srmPrepareToGet;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmPrepareToGet.srmPrepareToGetRequest = srmPrepareToGetRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmPrepareToGet(soap, &soap_tmp_ns1__srmPrepareToGet);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmPrepareToGet(soap, &soap_tmp_ns1__srmPrepareToGet, "ns1:srmPrepareToGet", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmPrepareToGet(soap, &soap_tmp_ns1__srmPrepareToGet, "ns1:srmPrepareToGet", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_21)
		return soap_closesock(soap);
	soap_default_ns1__srmPrepareToGetResponse_(soap, _param_21);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmPrepareToGetResponse_(soap, _param_21, "ns1:srmPrepareToGetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmStatusOfGetRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmStatusOfGetRequestRequest *srmStatusOfGetRequestRequest, struct ns1__srmStatusOfGetRequestResponse_ *_param_22)
{	struct ns1__srmStatusOfGetRequest soap_tmp_ns1__srmStatusOfGetRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmStatusOfGetRequest.srmStatusOfGetRequestRequest = srmStatusOfGetRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmStatusOfGetRequest(soap, &soap_tmp_ns1__srmStatusOfGetRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmStatusOfGetRequest(soap, &soap_tmp_ns1__srmStatusOfGetRequest, "ns1:srmStatusOfGetRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmStatusOfGetRequest(soap, &soap_tmp_ns1__srmStatusOfGetRequest, "ns1:srmStatusOfGetRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_22)
		return soap_closesock(soap);
	soap_default_ns1__srmStatusOfGetRequestResponse_(soap, _param_22);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmStatusOfGetRequestResponse_(soap, _param_22, "ns1:srmStatusOfGetRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmBringOnline(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmBringOnlineRequest *srmBringOnlineRequest, struct ns1__srmBringOnlineResponse_ *_param_23)
{	struct ns1__srmBringOnline soap_tmp_ns1__srmBringOnline;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmBringOnline.srmBringOnlineRequest = srmBringOnlineRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmBringOnline(soap, &soap_tmp_ns1__srmBringOnline);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmBringOnline(soap, &soap_tmp_ns1__srmBringOnline, "ns1:srmBringOnline", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmBringOnline(soap, &soap_tmp_ns1__srmBringOnline, "ns1:srmBringOnline", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_23)
		return soap_closesock(soap);
	soap_default_ns1__srmBringOnlineResponse_(soap, _param_23);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmBringOnlineResponse_(soap, _param_23, "ns1:srmBringOnlineResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmStatusOfBringOnlineRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmStatusOfBringOnlineRequestRequest *srmStatusOfBringOnlineRequestRequest, struct ns1__srmStatusOfBringOnlineRequestResponse_ *_param_24)
{	struct ns1__srmStatusOfBringOnlineRequest soap_tmp_ns1__srmStatusOfBringOnlineRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmStatusOfBringOnlineRequest.srmStatusOfBringOnlineRequestRequest = srmStatusOfBringOnlineRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmStatusOfBringOnlineRequest(soap, &soap_tmp_ns1__srmStatusOfBringOnlineRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmStatusOfBringOnlineRequest(soap, &soap_tmp_ns1__srmStatusOfBringOnlineRequest, "ns1:srmStatusOfBringOnlineRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmStatusOfBringOnlineRequest(soap, &soap_tmp_ns1__srmStatusOfBringOnlineRequest, "ns1:srmStatusOfBringOnlineRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_24)
		return soap_closesock(soap);
	soap_default_ns1__srmStatusOfBringOnlineRequestResponse_(soap, _param_24);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmStatusOfBringOnlineRequestResponse_(soap, _param_24, "ns1:srmStatusOfBringOnlineRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmPrepareToPut(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmPrepareToPutRequest *srmPrepareToPutRequest, struct ns1__srmPrepareToPutResponse_ *_param_25)
{	struct ns1__srmPrepareToPut soap_tmp_ns1__srmPrepareToPut;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmPrepareToPut.srmPrepareToPutRequest = srmPrepareToPutRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmPrepareToPut(soap, &soap_tmp_ns1__srmPrepareToPut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmPrepareToPut(soap, &soap_tmp_ns1__srmPrepareToPut, "ns1:srmPrepareToPut", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmPrepareToPut(soap, &soap_tmp_ns1__srmPrepareToPut, "ns1:srmPrepareToPut", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_25)
		return soap_closesock(soap);
	soap_default_ns1__srmPrepareToPutResponse_(soap, _param_25);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmPrepareToPutResponse_(soap, _param_25, "ns1:srmPrepareToPutResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmStatusOfPutRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmStatusOfPutRequestRequest *srmStatusOfPutRequestRequest, struct ns1__srmStatusOfPutRequestResponse_ *_param_26)
{	struct ns1__srmStatusOfPutRequest soap_tmp_ns1__srmStatusOfPutRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmStatusOfPutRequest.srmStatusOfPutRequestRequest = srmStatusOfPutRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmStatusOfPutRequest(soap, &soap_tmp_ns1__srmStatusOfPutRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmStatusOfPutRequest(soap, &soap_tmp_ns1__srmStatusOfPutRequest, "ns1:srmStatusOfPutRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmStatusOfPutRequest(soap, &soap_tmp_ns1__srmStatusOfPutRequest, "ns1:srmStatusOfPutRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_26)
		return soap_closesock(soap);
	soap_default_ns1__srmStatusOfPutRequestResponse_(soap, _param_26);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmStatusOfPutRequestResponse_(soap, _param_26, "ns1:srmStatusOfPutRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmCopy(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmCopyRequest *srmCopyRequest, struct ns1__srmCopyResponse_ *_param_27)
{	struct ns1__srmCopy soap_tmp_ns1__srmCopy;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmCopy.srmCopyRequest = srmCopyRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmCopy(soap, &soap_tmp_ns1__srmCopy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmCopy(soap, &soap_tmp_ns1__srmCopy, "ns1:srmCopy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmCopy(soap, &soap_tmp_ns1__srmCopy, "ns1:srmCopy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_27)
		return soap_closesock(soap);
	soap_default_ns1__srmCopyResponse_(soap, _param_27);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmCopyResponse_(soap, _param_27, "ns1:srmCopyResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmStatusOfCopyRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmStatusOfCopyRequestRequest *srmStatusOfCopyRequestRequest, struct ns1__srmStatusOfCopyRequestResponse_ *_param_28)
{	struct ns1__srmStatusOfCopyRequest soap_tmp_ns1__srmStatusOfCopyRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmStatusOfCopyRequest.srmStatusOfCopyRequestRequest = srmStatusOfCopyRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmStatusOfCopyRequest(soap, &soap_tmp_ns1__srmStatusOfCopyRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmStatusOfCopyRequest(soap, &soap_tmp_ns1__srmStatusOfCopyRequest, "ns1:srmStatusOfCopyRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmStatusOfCopyRequest(soap, &soap_tmp_ns1__srmStatusOfCopyRequest, "ns1:srmStatusOfCopyRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_28)
		return soap_closesock(soap);
	soap_default_ns1__srmStatusOfCopyRequestResponse_(soap, _param_28);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmStatusOfCopyRequestResponse_(soap, _param_28, "ns1:srmStatusOfCopyRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmReleaseFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmReleaseFilesRequest *srmReleaseFilesRequest, struct ns1__srmReleaseFilesResponse_ *_param_29)
{	struct ns1__srmReleaseFiles soap_tmp_ns1__srmReleaseFiles;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmReleaseFiles.srmReleaseFilesRequest = srmReleaseFilesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmReleaseFiles(soap, &soap_tmp_ns1__srmReleaseFiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmReleaseFiles(soap, &soap_tmp_ns1__srmReleaseFiles, "ns1:srmReleaseFiles", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmReleaseFiles(soap, &soap_tmp_ns1__srmReleaseFiles, "ns1:srmReleaseFiles", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_29)
		return soap_closesock(soap);
	soap_default_ns1__srmReleaseFilesResponse_(soap, _param_29);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmReleaseFilesResponse_(soap, _param_29, "ns1:srmReleaseFilesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmPutDone(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmPutDoneRequest *srmPutDoneRequest, struct ns1__srmPutDoneResponse_ *_param_30)
{	struct ns1__srmPutDone soap_tmp_ns1__srmPutDone;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmPutDone.srmPutDoneRequest = srmPutDoneRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmPutDone(soap, &soap_tmp_ns1__srmPutDone);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmPutDone(soap, &soap_tmp_ns1__srmPutDone, "ns1:srmPutDone", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmPutDone(soap, &soap_tmp_ns1__srmPutDone, "ns1:srmPutDone", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_30)
		return soap_closesock(soap);
	soap_default_ns1__srmPutDoneResponse_(soap, _param_30);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmPutDoneResponse_(soap, _param_30, "ns1:srmPutDoneResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmAbortRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmAbortRequestRequest *srmAbortRequestRequest, struct ns1__srmAbortRequestResponse_ *_param_31)
{	struct ns1__srmAbortRequest soap_tmp_ns1__srmAbortRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmAbortRequest.srmAbortRequestRequest = srmAbortRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmAbortRequest(soap, &soap_tmp_ns1__srmAbortRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmAbortRequest(soap, &soap_tmp_ns1__srmAbortRequest, "ns1:srmAbortRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmAbortRequest(soap, &soap_tmp_ns1__srmAbortRequest, "ns1:srmAbortRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_31)
		return soap_closesock(soap);
	soap_default_ns1__srmAbortRequestResponse_(soap, _param_31);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmAbortRequestResponse_(soap, _param_31, "ns1:srmAbortRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmAbortFiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmAbortFilesRequest *srmAbortFilesRequest, struct ns1__srmAbortFilesResponse_ *_param_32)
{	struct ns1__srmAbortFiles soap_tmp_ns1__srmAbortFiles;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmAbortFiles.srmAbortFilesRequest = srmAbortFilesRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmAbortFiles(soap, &soap_tmp_ns1__srmAbortFiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmAbortFiles(soap, &soap_tmp_ns1__srmAbortFiles, "ns1:srmAbortFiles", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmAbortFiles(soap, &soap_tmp_ns1__srmAbortFiles, "ns1:srmAbortFiles", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_32)
		return soap_closesock(soap);
	soap_default_ns1__srmAbortFilesResponse_(soap, _param_32);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmAbortFilesResponse_(soap, _param_32, "ns1:srmAbortFilesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmSuspendRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmSuspendRequestRequest *srmSuspendRequestRequest, struct ns1__srmSuspendRequestResponse_ *_param_33)
{	struct ns1__srmSuspendRequest soap_tmp_ns1__srmSuspendRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmSuspendRequest.srmSuspendRequestRequest = srmSuspendRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmSuspendRequest(soap, &soap_tmp_ns1__srmSuspendRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmSuspendRequest(soap, &soap_tmp_ns1__srmSuspendRequest, "ns1:srmSuspendRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmSuspendRequest(soap, &soap_tmp_ns1__srmSuspendRequest, "ns1:srmSuspendRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_33)
		return soap_closesock(soap);
	soap_default_ns1__srmSuspendRequestResponse_(soap, _param_33);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmSuspendRequestResponse_(soap, _param_33, "ns1:srmSuspendRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmResumeRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmResumeRequestRequest *srmResumeRequestRequest, struct ns1__srmResumeRequestResponse_ *_param_34)
{	struct ns1__srmResumeRequest soap_tmp_ns1__srmResumeRequest;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmResumeRequest.srmResumeRequestRequest = srmResumeRequestRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmResumeRequest(soap, &soap_tmp_ns1__srmResumeRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmResumeRequest(soap, &soap_tmp_ns1__srmResumeRequest, "ns1:srmResumeRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmResumeRequest(soap, &soap_tmp_ns1__srmResumeRequest, "ns1:srmResumeRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_34)
		return soap_closesock(soap);
	soap_default_ns1__srmResumeRequestResponse_(soap, _param_34);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmResumeRequestResponse_(soap, _param_34, "ns1:srmResumeRequestResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmGetRequestSummary(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmGetRequestSummaryRequest *srmGetRequestSummaryRequest, struct ns1__srmGetRequestSummaryResponse_ *_param_35)
{	struct ns1__srmGetRequestSummary soap_tmp_ns1__srmGetRequestSummary;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmGetRequestSummary.srmGetRequestSummaryRequest = srmGetRequestSummaryRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmGetRequestSummary(soap, &soap_tmp_ns1__srmGetRequestSummary);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmGetRequestSummary(soap, &soap_tmp_ns1__srmGetRequestSummary, "ns1:srmGetRequestSummary", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmGetRequestSummary(soap, &soap_tmp_ns1__srmGetRequestSummary, "ns1:srmGetRequestSummary", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_35)
		return soap_closesock(soap);
	soap_default_ns1__srmGetRequestSummaryResponse_(soap, _param_35);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmGetRequestSummaryResponse_(soap, _param_35, "ns1:srmGetRequestSummaryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmExtendFileLifeTime(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmExtendFileLifeTimeRequest *srmExtendFileLifeTimeRequest, struct ns1__srmExtendFileLifeTimeResponse_ *_param_36)
{	struct ns1__srmExtendFileLifeTime soap_tmp_ns1__srmExtendFileLifeTime;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmExtendFileLifeTime.srmExtendFileLifeTimeRequest = srmExtendFileLifeTimeRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmExtendFileLifeTime(soap, &soap_tmp_ns1__srmExtendFileLifeTime);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmExtendFileLifeTime(soap, &soap_tmp_ns1__srmExtendFileLifeTime, "ns1:srmExtendFileLifeTime", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmExtendFileLifeTime(soap, &soap_tmp_ns1__srmExtendFileLifeTime, "ns1:srmExtendFileLifeTime", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_36)
		return soap_closesock(soap);
	soap_default_ns1__srmExtendFileLifeTimeResponse_(soap, _param_36);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmExtendFileLifeTimeResponse_(soap, _param_36, "ns1:srmExtendFileLifeTimeResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmGetRequestTokens(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmGetRequestTokensRequest *srmGetRequestTokensRequest, struct ns1__srmGetRequestTokensResponse_ *_param_37)
{	struct ns1__srmGetRequestTokens soap_tmp_ns1__srmGetRequestTokens;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmGetRequestTokens.srmGetRequestTokensRequest = srmGetRequestTokensRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmGetRequestTokens(soap, &soap_tmp_ns1__srmGetRequestTokens);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmGetRequestTokens(soap, &soap_tmp_ns1__srmGetRequestTokens, "ns1:srmGetRequestTokens", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmGetRequestTokens(soap, &soap_tmp_ns1__srmGetRequestTokens, "ns1:srmGetRequestTokens", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_37)
		return soap_closesock(soap);
	soap_default_ns1__srmGetRequestTokensResponse_(soap, _param_37);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmGetRequestTokensResponse_(soap, _param_37, "ns1:srmGetRequestTokensResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmGetTransferProtocols(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmGetTransferProtocolsRequest *srmGetTransferProtocolsRequest, struct ns1__srmGetTransferProtocolsResponse_ *_param_38)
{	struct ns1__srmGetTransferProtocols soap_tmp_ns1__srmGetTransferProtocols;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmGetTransferProtocols.srmGetTransferProtocolsRequest = srmGetTransferProtocolsRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmGetTransferProtocols(soap, &soap_tmp_ns1__srmGetTransferProtocols);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmGetTransferProtocols(soap, &soap_tmp_ns1__srmGetTransferProtocols, "ns1:srmGetTransferProtocols", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmGetTransferProtocols(soap, &soap_tmp_ns1__srmGetTransferProtocols, "ns1:srmGetTransferProtocols", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_38)
		return soap_closesock(soap);
	soap_default_ns1__srmGetTransferProtocolsResponse_(soap, _param_38);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmGetTransferProtocolsResponse_(soap, _param_38, "ns1:srmGetTransferProtocolsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__srmPing(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__srmPingRequest *srmPingRequest, struct ns1__srmPingResponse_ *_param_39)
{	struct ns1__srmPing soap_tmp_ns1__srmPing;
	if (!soap_endpoint)
		soap_endpoint = "https://localhost:8443/ogsa/services/srm";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__srmPing.srmPingRequest = srmPingRequest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__srmPing(soap, &soap_tmp_ns1__srmPing);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__srmPing(soap, &soap_tmp_ns1__srmPing, "ns1:srmPing", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__srmPing(soap, &soap_tmp_ns1__srmPing, "ns1:srmPing", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_39)
		return soap_closesock(soap);
	soap_default_ns1__srmPingResponse_(soap, _param_39);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__srmPingResponse_(soap, _param_39, "ns1:srmPingResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
