#!/bin/bash

########################################################################
#
#   Filename:   digs-version
#
#   Authors:    Daragh Byrne, EPCC.
#
#   Purpose:    Reports version information for DiGS client installation
#
#   Contents:   Simple shell script.
#
#   Used in:    N/A.
#
#   Contact:    digs-enquiries@epcc.ed.ac.uk
#
#   Copyright (c) 2003-2008 The University of Edinburgh
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2 of the
#   License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston,
#   MA 02111-1307, USA.
#
#   As a special exception, you may link this program with code
#   developed by the OGSA-DAI project without such code being covered
#   by the GNU General Public License.
#
########################################################################

# Check for argument list -- normally there should be none.
if [ $# = 0 ]
then
    if test -f ${DIGS_HOME}/VERSION
    then
	cat ${DIGS_HOME}/VERSION
    else
	echo "File ${DIGS_HOME}/VERSION does not exist."
	echo "Check that DIGS_HOME environment is defined."
    fi
else
    # For non-empty arguement list, display brief usage
    echo "Usage: digs-version"
    echo "Display version information for DiGS installation"
fi
